### PR TITLE
Created PermissionSetField  

### LINKED ISSUE #29: Create PermissionSetField
**Is your feature request related to a problem? Please describe.**
We need a custom django model field to store our permissions as string and retieve it as python object as per our db design.
https://dbdiagram.io/d/5e97237739d18f5553fda63b

**Describe the solution you'd like**
1. Create a custom django model field which can automatically convert permissions into string for storing in the db and string into python object for using.
1. Place it in the org app
1. Write testcases to ensure proper functionality

### PR DESCRIPTION
**Pull request by sahil9001**
### Description
Added migrations of test model and more tests of CustomField(tests were added by @priyanshisharma ).
Modified `custom_model_field.py`

**Type of Change:** (Delete irrelevant options)
- Code
- Testing

**Code/Quality Assurance Only** (Delete irrelevant options)

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Ran `python manage.py test` and all 7 tests passed.

**Test output:**
```
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.......
----------------------------------------------------------------------
Ran 7 tests in 0.003s

OK
Destroying test database for alias 'default'...
```
### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Any dependent changes have been merged

**Code/Quality Assurance**
- [x] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by naveennvrgup — COMMENTED** [review]
1. @priyanshisharma @sahil9001 try to do with the help of the bitset technique as insisted by @BadduCoder in the meeting (instead of using the string). 
1. Use integerfield and make it positive only.
1. Also please modify the testcases accordingly 
1. :fire: great work on the test cases.

**Comment by sahil9001** [comment]
@naveennvrgup Sir, please review the PR once again.

**Comment by sumit-badsara** [comment]
@sahil9001 We aren't working with binary, check out @priyanshisharma PR, it's a bit relevant to what I was saying. (Working with integer, and bitset operations)
And as I said earlier, It's better to decide who is working on the PR. We don't want to waste your efforts, one issue one PR. Simple as that.
So, I don't want these clashes to happen again, we don't want to see someone's effort going in vein.
@sahil9001 @priyanshisharma.
Either inform the managers before or comment on the issue.

**Comment by sumit-badsara** [comment]
@sahil9001 Other than that, efforts are appreciated for this PR, good work :fire:

**Comment by sahil9001** [comment]
@BadduCoder  Thankyou sir, I'll keep that in mind next time.

**Comment by priyanshisharma** [comment]
Yeah @BadduCoder sir, we will take care of the clashes now onwards.

**Pull request closed without merging**
