### PR TITLE
Added View group api

### LINKED ISSUE #107: View Group API
Is your feature request related to a problem? Please describe.
As a staff of the organisation I would like to view the details of the groups under the org.

Describe the solution you'd like

1. Create an api: [get] /api/org/(org-id)/group/(group-id)/ .
3. only staff of that org can access this api.
4. Add necessary test cases.
5. make swagger docs for the same

sample 200 response:
```
{
    "id": 1,
    "name": "head coordinator",
    "role": "Managing the sub-ordinates. Supervising the work in the respective domains. Interaction with other domains...",
    "permissions": {
        "Is Admin":{
            value:  False, # whether this permission is granted or not
            perm_int: 1, # this perm_ints represents the integer value of this permission 
        },
        "Is Staff":{
            value: True,
            perm_int: 4,
        },
        "Can create tasks":{
            value: True,
            perm_int: 3,
        },
        "Can create groups":{
            value: True,
            perm_int: 6,
        },
        "Can reply to queries":{
            value:  False,
            perm_int: 5,
        }
    }
}
```

### PR DESCRIPTION
**Pull request by priyanshisharma**
### Description
I've added the API, that provides details of a particular group of an organisation to authorised members. It can be visited at `Org.views.GroupDetailsView`. Test Cases and Swagger docs for the same have also been added.

**Type of Change:** (Delete irrelevant options)
- Code
- Testing
- Documentation

**Code/Quality Assurance Only** (Delete irrelevant options)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Tests have been described in `tests.org.tests_view_group_api.py` and they run successfuly. The following is the result of executing `python3 manage.py test`. 
```
----------------------------------------------------------------------
Ran 49 tests in 9.100s

OK
Destroying test database for alias 'default'...
```

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [x] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Review by sumit-badsara — COMMENTED** [review]
Great work! Code seems perfect to me 🎉 ! Will test it our locally later.
Perfect usage of `get() instead of filter()` and catching the exception. Nice work! 👍

**Review by naveennvrgup — APPROVED** [review]
1. Great job with code quality :medal_military: 
1. The tests are on point. :clap: Really appreciate the use of 12345 for invalid group and org id
1. `{"message":"This organization does not exist"}` and similar responses can be replaced with `responses.org_not_present_404`  and equivalents in the view function, as it is static and increases reusability.
1. in the future error responses use `detail` instead of `message` as a key. (as per the discussion on slack :innocent: )

3 & 4 are minor things so create  `good first issue` for both of them

**Comment by naveennvrgup** [comment]
1. test locally works as expected
1. merging

**Comment by naveennvrgup** [comment]
> Great work! Code seems perfect to me  ! Will test it our locally later.
> Perfect usage of `get() instead of filter()` and catching the exception. Nice work!

A approval would be better choice here :innocent:. Than just comment 
image

**Comment by sumit-badsara** [comment]
> 
> 
> > Great work! Code seems perfect to me  ! Will test it our locally later.
> > Perfect usage of `get() instead of filter()` and catching the exception. Nice work!
> 
> A approval would be better choice here 😇. Than just comment
> image

Approving without testing ? 😢

**Comment by priyanshisharma** [comment]
> 3 & 4 are minor things so create `good first issue` for both of them

I've created issue #114 and #113 respectively for them. 😄

**Pull request merged**
