### PR TITLE
Add permission to list org api

### LINKED ISSUE #136: add permission details to /users/org/ API
**Is your feature request related to a problem? Please describe.**
As a developer of teesco app/web it is necessary to have the permissions info of users in a org to provide tailored experience.

**Describe the solution you'd like**
Update `/user/org/` API to return permissions of the user in each org(along with all previous info).
The new response should have an array like this
```
[
  {
    "id": 1,
    "org_name": "E Cell",
    "user_role": "Admin",
    "profile_pic": "null",
    "route_slug": "0-e-cell",
    "tagline": "Leader Beyond Borders"
    "permissions": {
        "Is Admin": {
            "value": false,
            "perm_int": 1
        },
        "Is Staff": {
            "value": true,
            "perm_int": 4
        },
        "Can create tasks": {
            "value": true,
            "perm_int": 3
        },
        "Can create groups": {
            "value": true,
            "perm_int": 6
        },
        "Can reply to queries": {
            "value": false,
            "perm_int": 5
        }
    },
    // other similar org objects
]
```

### PR DESCRIPTION
**Pull request by priyanshisharma**
### Description
I've added the permissions in the `response_object` defined in `users.views.list_orgs_view` and also updated `list_orgs_200` in `users.responses.py`.

**Type of Change:** (Delete irrelevant options)
- Code

**Code/Quality Assurance Only** (Delete irrelevant options)

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
All previously defined tests run successfully. No new tests have been added.
```
System check identified no issues (0 silenced).
.................................................................................
----------------------------------------------------------------------
Ran 81 tests in 17.717s

OK
```
Tested locally and works as expected.
Screen Shot 2020-06-14 at 12 46 25 PM

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged
- [ ] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance**
- [x] My changes generate no new warnings 
- [x] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Review by sahil9001 — CHANGES_REQUESTED** [review]
Screenshot from 2020-06-15 10-53-43

Responses with codes `404` and `400` are not documented in the swagger docs, while it is used in the `views.py`

**Comment by priyanshisharma** [comment]
> Responses with codes `404` and `400` are not documented in the swagger docs, while it is used in the `views.py`

@sahil9001 Under what scenario is a `400` and `404` expected according to you?
According to me if a user doesn't belong to any org, it receives an empty list which should be just fine as is.

**Comment by sahil9001** [comment]
Yeah I guess that's fine then.

**Review by sahil9001 — APPROVED** [review]

**Review by naveennvrgup — APPROVED** [review]
1. Tested locally works great :fire: 
:+1:  for review @sahil9001

**Pull request merged**
