### PR TITLE
Fixes #9

### LINKED ISSUE #9: Create django app - users
**Is your feature request related to a problem? Please describe.**
We need a django app to create python logic for users and user related operations.

**Describe the solution you'd like**
1. create django app **users**.
2. add the app to settings.py
3. create urls.py under users app
4. include **users/urls.py** in the **server/urls.py** with prefix **api/users/**

### PR DESCRIPTION
**Pull request by sahil9001**
### Description
Added 'users' app and modified settings.py to include 'users' app, also modified server/urls.py to add 
'api/users/' route.

**Type of Change:** (Delete irrelevant options)
- Code

**Code/Quality Assurance Only** (Delete irrelevant options)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.
- Ran django project by `python manage.py runserver`.
- Worked fine on `localhost:8080`

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged
- [ ] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by sahil9001** [comment]
@naveennvrgup

**Review by naveennvrgup — APPROVED** [review]
Looks great! Nice job :+1:

**Comment by naveennvrgup** [comment]
Glad to see that you followed conventions for branch name and used PR template :fire: Please follow the commit conventions from next time.

**Comment by PratibhaShrivastav** [comment]
@naveennvrgup @sahil9001 The PR title should have been more informative. Also there is a need to uncheck the irrelevant options like `I have added tests... `

**Comment by sahil9001** [comment]
As there's nothing to test apart from 'users' app now, I've only ran the server locally which is the 'test' you are asking for.

**Comment by PratibhaShrivastav** [comment]
@sahil9001 That's okay. The option for tests is to be checked only when you add some django tests for your code.

**Pull request merged**
